export const SIGNUP = 'SIGNUP'
export const SIGNIN = 'SIGNIN'
export const GOOGLESIGNIN = 'GOOGLESIGNIN'
export const SIGNOUT = 'SIGNOUT'
export const FORGOTPASSWORD = 'FORGOTPASSWORD'

export const FETCH_CATEGORY = "FETCH_CATEGORY"
export const ADD_CATEGORY = "ADD_CATEGORY"
export const REMOVE_CATEGORY = "REMOVE_CATEGORY"
export const UPDATE_CATEGORY = "UPDATE_CATEGORY"

export const LOADINGAUTH = 'LOADINGAUTH'
export const LOADINGCATEGORY = 'LOADINGCATEGORY'
export const ERRORAUTH = 'ERRORAUTH'
export const ERRORCATEGORY = 'ERRORCATEGORY'
