export const SIGNUP = 'SIGNUP'
export const SIGNIN = 'SIGNIN'
export const GOOGLESIGNIN = 'GOOGLESIGNIN'
export const SIGNOUT = 'SIGNOUT'
export const FORGOTPASSWORD = 'FORGOTPASSWORD'
// WebsiteSide
export const FETCH_CATEGORY_SITE = "FETCH_CATEGORY_SITE"
// AdminSide
export const FETCH_CATEGORY = "FETCH_CATEGORY"
export const ADD_CATEGORY = "ADD_CATEGORY"
export const REMOVE_CATEGORY = "REMOVE_CATEGORY"
export const UPDATE_CATEGORY = "UPDATE_CATEGORY"

export const LOADINGAUTH = 'LOADINGAUTH'
export const LOADINGCATEGORY = 'LOADINGCATEGORY'
export const LOADING_CATEGORY_SITE = 'LOADING_CATEGORY_SITE'
export const ERROR_CATEGORY_SITE = 'ERROR_CATEGORY_SITE'
export const ERRORAUTH = 'ERRORAUTH'
export const ERRORCATEGORY = 'ERRORCATEGORY'
