export const SIGNUP = 'SIGNUP'
export const SIGNIN = 'SIGNIN'
export const GOOGLESIGNIN = 'GOOGLESIGNIN'
export const SIGNOUT = 'SIGNOUT'
export const FORGOTPASSWORD = 'FORGOTPASSWORD'
// WebsiteSide
export const FETCH_CATEGORY_SITE = "FETCH_CATEGORY_SITE"
export const FETCH_PRODUCT_SITE = "FETCH_PRODUCT_SITE"
export const FETCH_CART = "FETCH_CART"
export const ADD_CART_ITEM = "ADD_CART_ITEM"
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM"
export const DELETE_CART_ITEM = "DELETE_CART_ITEM"

// AdminSide
export const FETCH_CATEGORY = "FETCH_CATEGORY"
export const ADD_CATEGORY = "ADD_CATEGORY"
export const REMOVE_CATEGORY = "REMOVE_CATEGORY"
export const UPDATE_CATEGORY = "UPDATE_CATEGORY"
export const FETCH_PRODUCTS = "FETCH_PRODUCTS"
export const ADD_PRODUCTS = "ADD_PRODUCTS"
export const REMOVE_PRODUCTS = "REMOVE_PRODUCTS"
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS"
export const FETCH_ORDER_ADM = "FETCH_ORDER_ADM"


export const LOADING_FETCH_ORDER_ADM = "LOADING_FETCH_ORDER_ADM"
export const ERROR_FETCH_ORDER_ADM = "ERROR_FETCH_ORDER_ADM"
export const LOADING_PRODUCT = "LOADING_PRODUCT"
export const ERROR_PRODUCT = "ERROR_PRODUCT"
export const LOADINGAUTH = 'LOADINGAUTH'
export const LOADINGCATEGORY = 'LOADINGCATEGORY'
export const LOADING_CATEGORY_SITE = 'LOADING_CATEGORY_SITE'
export const ERROR_CATEGORY_SITE = 'ERROR_CATEGORY_SITE'
export const LOADING_PRODUCT_SITE = 'LOADING_PRODUCT_SITE'
export const ERROR_PRODUCT_SITE = 'ERROR_PRODUCT_SITE'
export const ERRORAUTH = 'ERRORAUTH'
export const ERRORCATEGORY = 'ERRORCATEGORY'
